# -*- coding: utf-8 -*-
"""INNOMATICS--Logic-Building-Task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oosxGX4-340qD7Nqr7UarvclXA95aqUR
"""

username = "admin"
password = "1234"

if username == "admin" and password == "1234":
    print("Login Successful")
else:
    print("Invalid Credentials")

marks = [45, 78, 90, 33, 60]
pass_count = 0
fail_count = 0
for mark in marks:
    if mark >= 50:
        pass_count += 1
    else:
        fail_count += 1
print(f"Total Pass Students: {pass_count}")
print(f"Total Fail Students: {fail_count}")

names = ["  Alice ", "bob", " CHARLIE "]
cleaned_names = [name.strip().lower() for name in names]
print(f"Original Names: {names}")
print(f"Cleaned Names: {cleaned_names}")

messages = ["Hi", "Welcome to the platform", "OK"]
for msg in messages:
    length = len(msg)
    if length > 10:
        print(f"'{msg}' - Length: {length} [FLAGGED: Too Long]")
    else:
        print(f"'{msg}' - Length: {length}")

logs = ["INFO", "ERROR", "WARNING", "ERROR"]
error_count = 0
for log in logs:
    if log == "ERROR":
        error_count += 1
print(f"Total Errors Found: {error_count}")